/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lance_decode_FFmpeg */

#ifndef _Included_org_lance_decode_FFmpeg
#define _Included_org_lance_decode_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lance_decode_FFmpeg_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    jniIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_lance_decode_FFmpeg_jniIntArray
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    play
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lance_decode_FFmpeg_play
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avRegisterAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lance_decode_FFmpeg_avRegisterAll
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avOpenInputFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_avOpenInputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    initFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_initFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avFindStreamInfo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_avFindStreamInfo
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    findVideoStream
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_findVideoStream
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avcodecFindDecoder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_avcodecFindDecoder
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avcodecOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_avcodecOpen
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avcodecAllocFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lance_decode_FFmpeg_avcodecAllocFrame
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lance_decode_FFmpeg_avFree
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avcodecClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lance_decode_FFmpeg_avcodecClose
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    avCloseInputFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lance_decode_FFmpeg_avCloseInputFile
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    getCodecName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lance_decode_FFmpeg_getCodecName
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lance_decode_FFmpeg_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lance_decode_FFmpeg_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    getBitRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lance_decode_FFmpeg_getBitRate
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    allocateBuffer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lance_decode_FFmpeg_allocateBuffer
  (JNIEnv *, jobject);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    setScreenSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lance_decode_FFmpeg_setScreenSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lance_decode_FFmpeg
 * Method:    getNextDecodedFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_lance_decode_FFmpeg_getNextDecodedFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
